<?php
/**
 * @file
 * Contains theme override functions and preprocess functions
 */

use Drupal\Core\Template\RenderWrapper;
use Drupal\Core\Template\Attribute;
use Drupal\Component\Utility\Html;
use Drupal\Component\Utility\Xss;
use Drupal\search\Form\SearchBlockForm;
use Drupal\Component\Utility\SafeMarkup;
use Drupal\Core\Form\FormStateInterface;
use Drupal\system\Form\ThemeSettingsForm;
use Drupal\file\Entity\File;
use Drupal\Core\Url;
use Drupal\file\Plugin\Core\Entity\FileInterface;
use Drupal\Core\Config\ConfigFactoryInterface;
  
/**
 * Implements hook_preprocess_page() for block templates.
 */

function acadmix_preprocess_page(&$variables) {

  // Social media global variable.
  $variables['show_social_icon'] = theme_get_setting('show_social_icon');
  $variables['facebook_url'] = theme_get_setting('facebook_url');
  $variables['google_plus_url'] = theme_get_setting('google_plus_url');
  $variables['twitter_url'] = theme_get_setting('twitter_url');
  $variables['linkedin_url'] = theme_get_setting('linkedin_url');

  $variables['show_topnav_branding'] = theme_get_setting('show_topnav_branding');
  $variables['topnav_branding_text'] = theme_get_setting('topnav_branding_text');
  $variables['topnav_branding_url'] = theme_get_setting('topnav_branding_text');

  //To get the current URL
  $current_url  = \Drupal::request()->getRequestUri();
  $current_path = explode("/", $current_url);
  $variables['current_path'] = $current_path[2];

}
/**
 * @file
 * Bootstrap sub-theme.
 *
 * Place your custom PHP code in this file.
 */
/**
 * Implements hook_preprocess_HOOK() for block templates.
 */


function acadmix_preprocess_block(&$variables) {
  global $base_path;
  switch ($variables['base_plugin_id']) {
    case 'system_branding_block':
      $variables['site_logo'] = '';
      if ($variables['content']['site_logo']['#access'] && $variables['content']['site_logo']['#uri']) {
        $variables['site_logo'] = str_replace('.svg', '.png', $variables['content']['site_logo']['#uri']);
      }
      $variables['logo2'] = $base_path.'/' . drupal_get_path('theme','acadmix') . '/logo2.png';
      break;

  }
}


/**
 * Implements hook_form_system_theme_settings_alter().
 */
function acadmix_form_system_theme_settings_alter(&$form, \Drupal\Core\Form\FormStateInterface $form_state) {

      //Social Icon Link
      $form['acadmix_settings']['social_icon'] = array(
        '#type' => 'details',
        '#title' => t('Social Media Link'),
        '#collapsible' => TRUE,
        '#collapsed' => FALSE,
      );
      $form['acadmix_settings']['social_icon']['show_social_icon'] = array(
        '#type' => 'checkbox',
        '#title' => t('Show Social Icons'),
        '#default_value' => theme_get_setting('show_social_icon'),
        '#description'   => t("Show/Hide Social media links"),
      );
      $form['acadmix_settings']['social_icon']['facebook_url'] = array(
        '#type' => 'textfield',
        '#title' => t('Facebook URL'),
        '#default_value' => theme_get_setting('facebook_url'),
      );
      $form['acadmix_settings']['social_icon']['google_plus_url'] = array(
        '#type' => 'textfield',
        '#title' => t('Google plus URL'),
        '#default_value' => theme_get_setting('google_plus_url'),
      );
      $form['acadmix_settings']['social_icon']['twitter_url'] = array(
        '#type' => 'textfield',
        '#title' => t('Twitter URL'),
        '#default_value' => theme_get_setting('twitter_url'),
      );
      $form['acadmix_settings']['social_icon']['linkedin_url'] = array(
        '#type' => 'textfield',
        '#title' => t('LinkedIn URL'),
        '#default_value' => theme_get_setting('linkedin_url'),
      );

      $form['acadmix_settings']['topnav_branding'] = array(
        '#type' => 'details',
        '#title' => t('Top nav Branding'),
        '#collapsible' => TRUE,
        '#collapsed' => FALSE,
      );
      $form['acadmix_settings']['topnav_branding']['show_topnav_branding'] = array(
        '#type' => 'checkbox',
        '#title' => t('Show Top Nav Branding'),
        '#default_value' => theme_get_setting('show_topnav_branding'),
        '#description'   => t("Show/Hide Top Nav Branding"),
      );
      $form['acadmix_settings']['topnav_branding']['topnav_branding_text'] = array(
        '#type' => 'textfield',
        '#title' => t('Top Nav Branding Text'),
        '#default_value' => theme_get_setting('topnav_branding_text'),
      );
      $form['acadmix_settings']['topnav_branding']['topnav_branding_url'] = array(
        '#type' => 'textfield',
        '#title' => t('Top Nav Branding URL'),
        '#default_value' => theme_get_setting('topnav_branding_url'),
      );

      $form['acadmix_info'] = array(
        '#markup' => '<div class="messages messages--warning">Clear cache after making any changes in theme settings. <a href="../../config/development/performance">Click here to clear cache</a></div>'
      );
  }